### ISSUE TITLE
[meta] all-projects-directory is not listed

### ISSUE THREAD

**Issue by fire17** [catherineisonline/all-projects-directory#1]
Hi there
Just noticed this repo is not on it's own list
I think it should :)
Was wondering if it's auto updating somehow?
Thanks a lot and have a good one!

**Comment by catherineisonline** [comment]
Hello. This repository is not on this list because this list includes projects and this repository is not a project, it's a simple list to easier navigate across projects. If you already are on this repository you will not need an additional link to open this repository because you already are on this repository. And no, it's not updating automatically, I need to update it myself which I will try to do asap.  😊
